### ISSUE TITLE
Enabling a kafka producer seems to result in invincible processes

### ISSUE THREAD

**Issue by atamon** [Yolean/kafka-cache#19]
At least they won't shutdown by themselves, so someone has to force them.

Minimal repro:
```js
const KakfaCache = require('kafka-cache');

process.on('unhandledRejection', (err, p) => {
  console.error(err);
  console.error(p);
  if (err.message === 'This should shut shit down!') process.exit(0);
  else process.exit(1);
});

async function run() {

  const cache = KakfaCache.create({
    kafkaHost: 'kafka:9092',
    topic: 'foobar',
    readOnly: false
  });

  await cache.onReady();

  throw new Error('This should shut shit down!');
}

run();
```

**Comment by atamon** [comment]
In a production-stop triggering this behavior we also saw this error:

```
# Internal application stack trace ...
at KafkaConsumer.kafka.stream.message (/usr/src/app/src/db.js:74:5)
at KafkaConsumer.emit (events.js:182:13)
at readCallback (/usr/local/lib/node_modules/node-rdkafka/lib/kafka-consumer.js:421:12)
/usr/local/lib/node_modules/node-rdkafka/lib/producer.js:241
throw new Error('Producer not connected');
^

Error: Producer not connected
at Producer.flush (/usr/local/lib/node_modules/node-rdkafka/lib/producer.js:241:11)
at Producer.disconnect (/usr/local/lib/node_modules/node-rdkafka/lib/producer.js:284:8)
at process.on (/usr/src/yolean-kafka-cache/lib/kafka.js:62:39)
at process.emit (events.js:187:15)
at process.exit (internal/process.js:160:15)
at db.stream (/usr/src/app/index.js:183:19)
at KafkaConsumer.kafka.stream.message (/usr/src/app/src/db.js:74:5)
at KafkaConsumer.emit (events.js:182:13)
at readCallback (/usr/local/lib/node_modules/node-rdkafka/lib/kafka-consumer.js:421:12)
```

**Comment by solsson** [comment]
Invincible or invisible, or maybe inappropriate or inconvenient or indefinite?

**Comment by solsson** [comment]
Our line in the stacktrace is https://github.com/Yolean/kafka-cache/blob/e7de33695d56db2d5e44b3123691066be833b69d/lib/kafka.js#L62. Did you check for processes after running the repro case? What happens, the node process doesn't exit, or it hangs with a CPU spike?

**Comment by solsson** [comment]
Is #3 possibly related, or maybe the node-rdkafka issue referenced from #3?
